/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graduation_project;

import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ali
 */
public class Enter extends javax.swing.JDialog {

    public int qual ;
    public Enter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
         this.setLocationRelativeTo(null);
    }
    
    public static  String national  ="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        nationality = new javax.swing.JComboBox();
        qulalification = new javax.swing.JComboBox();
        state_qid = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        telephone = new javax.swing.JTextField();
        religion = new javax.swing.JComboBox();
        gendr = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        set_num = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        state = new javax.swing.JComboBox();
        disable = new javax.swing.JCheckBox();
        son = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("البيانات الشخصية الكاملة للطالب ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "البيانات الشخصية \n", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("الرقم القومي ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("الاسم ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("الجنسية ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("المؤهل ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("حالة القيد");

        id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });

        name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        nationality.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nationality.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "مصر", "اجنبي" }));

        qulalification.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qulalification.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "علمى علوم", "علمى رياضه", "ادبى", "مؤهلات" }));

        state_qid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        state_qid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "مستجد", "محول ", "باقي ", "معادلة", " " }));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graduation_project/download.png"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("رقم التليفون");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("الديانة");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("النوع");

        telephone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        telephone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        telephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telephoneKeyPressed(evt);
            }
        });

        religion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        religion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "مسلم ", "مسيحي" }));

        gendr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gendr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ذكر", "انثى" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("اختر صورة");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("رقم الجلوس");

        set_num.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        set_num.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        set_num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                set_numKeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("الحالة");

        state.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        state.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "انتظام ", "انتساب" }));

        disable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        disable.setText("ذوي الاحتياجات الخاصة ");

        son.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        son.setText("ابناءالعاملين ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(religion, javax.swing.GroupLayout.Alignment.LEADING, 0, 131, Short.MAX_VALUE)
                            .addComponent(gendr, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(state, javax.swing.GroupLayout.Alignment.LEADING, 0, 131, Short.MAX_VALUE)
                            .addComponent(set_num, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(telephone)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(son)))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19)
                        .addComponent(jLabel17))
                    .addComponent(jLabel25)
                    .addComponent(jLabel18))
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(id))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(qulalification, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(state_qid, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(disable))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(5, 5, 5)))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(set_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gendr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(qulalification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(state_qid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disable)
                    .addComponent(son))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("تعديل");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("ادخال ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("حذف");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("بحث");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("تفريخ الحقول");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("الغاء");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("ادخال درجاته");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton3, jButton4, jButton5, jButton7});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton3, jButton4, jButton5, jButton6, jButton7});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public  boolean validate_ssn(String s )
    {
        char [] c = s.toCharArray();
        for(int i =0 ;i<c.length;i++)
        {
            if (c[i] >= '0' && c[i]<= '9') {
           
        }
            else return true;
            
    }
        return false;
    }
   
    
    public boolean validate_name(String n )
    {
        if(n.equals(null)) return false ;
        else return true; 
    }
        
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
       String ssn ,nm ,telephonee;
       int gender, qualify,nationality,religion,stateq,setno,state,son,disable;
       
       telephonee=telephone.getText().trim();
       
       ssn=id.getText().trim(); 
       
       if(ssn==""||(ssn.length()!=14)||(validate_ssn(ssn)))
       { Dbase.op("الرقم القومي غير صحيح "); return ; }
       
       nm=name.getText().trim();  if(nm.equals("")){Dbase.op("ادخل الاسم "); return ;}
       nationality=this.nationality.getSelectedIndex()+1; 
       religion=this.religion.getSelectedIndex()+1;
       gender=this.gendr.getSelectedIndex()+1;
       stateq=this.state_qid.getSelectedIndex();
       qualify=this.qulalification.getSelectedIndex();  
       qual=qualify;
        System.out.println(qual);
       state=this.state.getSelectedIndex();
       if(this.set_num.getText().equals("")){Dbase.op("من فضلك ادخل رقم الجلوس "); return;}
       else
       {
       setno=Integer.parseInt(this.set_num.getText().trim());
       }
       if(this.son.isSelected()==true)
           son=1;
       else 
           son=0;
        if(this.disable.isSelected()==true)
           disable=1;
       else 
           disable=0;
        
         Calendar now = Calendar.getInstance();   // Gets the current date and time
         int year = now.get(Calendar.YEAR);
       try{
           if(file!=null)
           {
       String sql2="INSERT INTO `student` (`name`, `ssn`, `nationality`, `qualification`"
               + ", `phone`, `year`, `set_no`, `dept_id`, `gend_id`, `relig_id`, `personImage`"
               + ", `state`, `sons_of_employees`, `disAble`,  `stateRestriction`) "
               + "VALUES (?,?,?,?,?,?,?,-1,?,?,LOAD_FILE(?),?,?,?,?);";
       
       
      
	  Dbase.st = Dbase.getConnection().prepareStatement(sql2);
          Dbase.st.setString(1, nm);
          Dbase.st.setString(2, ssn);
          Dbase.st.setInt(3,nationality);
          Dbase.st.setInt(4,qualify);
          Dbase.st.setString(5,telephonee);
          Dbase.st.setInt(6,year);
           Dbase.st.setInt(7,setno);
           Dbase.st.setInt(8,gender);
          Dbase.st.setInt(9,religion);
          Dbase.st.setString(10,file.getPath());
          Dbase.st.setInt(11,state);
          Dbase.st.setInt(12,son);
          Dbase.st.setInt(13,disable);
          Dbase.st.setInt(14,stateq);
         
   
          
          Dbase.st.executeUpdate();
          Dbase.op("تم الادخال بنجاح ");
          this.clear(); 
        System.out.println(file.getPath().toString());
           }
           else
           {
               String sql2="INSERT INTO `student` (`name`, `ssn`, `nationality`, `qualification`"
               + ", `phone`, `year`, `set_no`, `dept_id`, `gend_id`, `relig_id`, `personImage`"
               + ", `state`, `sons_of_employees`, `disAble`,  `stateRestriction`) "
               + "VALUES (?,?,?,?,?,?,?,-1,?,?,?,?,?,?,?);";
       
       
      
	  Dbase.st = Dbase.getConnection().prepareStatement(sql2);
          Dbase.st.setString(1, nm);
          Dbase.st.setString(2, ssn);
          Dbase.st.setInt(3,nationality);
          Dbase.st.setInt(4,qualify);
          Dbase.st.setString(5,telephonee);
           Dbase.st.setInt(6,year);
           Dbase.st.setInt(7,setno);
           Dbase.st.setInt(8,gender);
          Dbase.st.setInt(9,religion);
          Dbase.st.setString(10,"NULL");
          Dbase.st.setInt(11,state);
          Dbase.st.setInt(12,son);
          Dbase.st.setInt(13,disable);
          Dbase.st.setInt(14,stateq); 
           
          Dbase.st.executeUpdate();
          Dbase.op("تم الادخال بنجاح ");
          this.clear();
           }
           file=null;
           
           national =ssn;
       }
       catch(com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException e)
       {
           Dbase.op("الرقم القومي مكرر ");
       }
      
       catch(Exception ex)
       {
           Dbase.op("لم يتم الادخال");
           System.out.println(ex.toString());
       }    
    }//GEN-LAST:event_jButton3ActionPerformed
 
      public Image resizeimage(Image img,int w,int h)
     {
         BufferedImage reimg = new BufferedImage(w,h,BufferedImage.TYPE_INT_ARGB);
         Graphics2D g = reimg.createGraphics();
         g.drawImage(img, 0, 0,w,h,null);
         g.dispose();
         return  reimg;
     }
    FileInputStream fin;  File file=null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          byte [] personimage =null;
         JFileChooser f =new JFileChooser();
            f.showOpenDialog(null);
           file = f.getSelectedFile();
            try{
              fin  = new FileInputStream(file);
                ByteArrayOutputStream bo = new ByteArrayOutputStream();
                byte [] buf  =new byte[1024];
                for(int i; (i=fin.read(buf))!=-1; )
                {
                  bo.write(buf, 0, i);
                }
                personimage =bo.toByteArray();
                ImageIcon im =new ImageIcon(personimage);
                jLabel14.setIcon(new ImageIcon(resizeimage(im.getImage(),jLabel14.getWidth(),jLabel14.getHeight())));          
            }catch(Exception e)
            { 
                
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        String sql ="SELECT * FROM `student` where ssn like '"+this.id.getText().trim()+"'"; 
        
        ResultSet rs =Dbase.executeSelect(sql);
        
        try
        {
        if(rs.next())
        {
            //setSelectedIndex
         name.setText(rs.getString("name"));
         nationality.setSelectedIndex(rs.getInt("nationality")-1);
         qulalification.setSelectedIndex(rs.getInt("qualification"));
         state_qid.setSelectedIndex(rs.getInt("stateRestriction"));
         state.setSelectedIndex(rs.getInt("state"));
         set_num.setText(rs.getString("set_no"));
         gendr.setSelectedIndex(rs.getInt("gend_id")-1);
         telephone.setText(rs.getString("phone"));
         religion.setSelectedIndex(rs.getInt("relig_id")-1);
         //card_date.setText(rs.getString("card_date"));
         if(rs.getInt("disAble")==1)
         {
         this.disable.setSelected(true);
         } else {this.disable.setSelected(false);}
         
        
            if(rs.getInt("sons_of_employees")==1)
         {
         this.son.setSelected(true);
         } else {this.son.setSelected(false);}
         byte image [] = rs.getBytes("personImage");
          ImageIcon ic=new ImageIcon(image);
          if(ic!=null){
          jLabel14.setIcon(new ImageIcon(resizeimage(ic.getImage(), jLabel14.getWidth(),jLabel14.getHeight())));  
          }
          else
          {
               jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graduation_project/download.png"))); 
          }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "هذا  الطالب غير موجود ");
        }
        }
        catch(SQLException s)
        {
            System.err.println( s.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        
        String sql="DELETE FROM `student` WHERE ssn LIKE '"+id.getText().trim()+"'";
        
            if(Dbase.executeSql(sql)==1)
            {
                
                Dbase.op("تم حذف الطالب بنجاح");
                this.clear();
            }
            else
            {
                Dbase.op("لم يتم حذف الطالب");
            }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        this.clear();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      
        this.dispose();;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String ssn ,nm ,telephonee,year;
        int gender,son,disable, qualify,nationality,religion,state,qid,setno;
        
       telephonee=telephone.getText().trim();
      ssn = this.id.getText().trim();
     if(ssn==""||(ssn.length()!=14)||(validate_ssn(ssn)))
       { Dbase.op("الرقم القومي غير صحيح "); return ; }
       
       nm=name.getText().trim();  if(nm.equals("")){Dbase.op("ادخل الاسم "); return ;}
      // city=this.city.getText().trim();
       
       nationality=this.nationality.getSelectedIndex()+1;
      
       religion=this.religion.getSelectedIndex()+1;
       
       gender=this.gendr.getSelectedIndex()+1;
       state=this.state.getSelectedIndex();
       qid=this.state_qid.getSelectedIndex();
       qualify=this.qulalification.getSelectedIndex();
       
     if(this.set_num.getText().equals("")){Dbase.op("من فضلك ادخل رقم الجلوس "); return;}
       else
       {
       setno=Integer.parseInt(this.set_num.getText().trim());
       }
        if(this.son.isSelected()==true)
           son=1;
       else 
           son=0;
        if(this.disable.isSelected()==true)
           disable=1;
       else 
           disable=0;
        
       try{
           String sql="UPDATE `student` SET `name`='"+nm+"'"
                   + ",`ssn`='"+ssn+"',`nationality`="+nationality+",`qualification`='"+qualify+"'"
                   + ",`phone`='"+telephonee+"',`set_no`='"+setno+"'"
                   + ",`gend_id`="+gender+",`relig_id`="+religion+""
                   + ",`state`="+state+",`sons_of_employees`="+son+",`disAble`="+disable+""
                   + ",`stateRestriction`="+state+" WHERE ssn='"+ssn+"'";
           if(file!=null)
           {
           sql="UPDATE `student` SET `name`='"+nm+"'"
                   + ",`ssn`='"+ssn+"',`nationality`="+nationality+",`qualification`='"+qualify+"'"
                   + ",`phone`='"+telephonee+"',`set_no`='"+setno+"'"
                   + ",`gend_id`="+gender+",`relig_id`="+religion+",`personImage`=LOAD_FILE(?)"
                   + ",`state`="+state+",`sons_of_employees`="+son+",`disAble`="+disable+""
                   + ",`stateRestriction`="+state+" WHERE ssn='"+ssn+"'";
          Dbase.st = Dbase.getConnection().prepareStatement(sql);
          Dbase.st.setString(1,file.getPath());
          Dbase.st.executeUpdate();
         
          Dbase.op("تم التعدبل بنجاح "); 
           }
           else 
           {
             
          Dbase.st = Dbase.getConnection().prepareStatement(sql);
          Dbase.st.executeUpdate();
          Dbase.op("تم التعدبل بنجاح ");
               
           } 
         
           } catch (SQLException ex) {
            Logger.getLogger(Enter.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(Exception ex)
        {
          System.out.println(ex);
          Dbase.op(ex.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
      
    }//GEN-LAST:event_idActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped

    }//GEN-LAST:event_idKeyTyped

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_idKeyPressed

    private void set_numKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_set_numKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_set_numKeyPressed

    private void telephoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneKeyPressed
        // TODO add your handling code here:
   

        
    }//GEN-LAST:event_telephoneKeyPressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
       if(this.qual==0)
           new grades1_Elmy3loom(null,true).setVisible(true);
       else if(this.qual==1)
           new grades1_ElmyRyada(null,true).setVisible(true);
       else if(this.qual==2)
           new grades1Adaby(null,true).setVisible(true);
       else 
           new grades(null,true).setVisible(true);
        
    }//GEN-LAST:event_jButton8ActionPerformed
    
    public void clear()
    {
       
        //this.city.setText(null);
     
        this.id.setText(null);
        
        this.name.setText(null);
       
        
        this.setName(null);
        this.telephone.setText(null);
   
        this.set_num.setText(null);
         jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graduation_project/download.png"))); 
         nationality.setSelectedIndex(0);
         
         this.gendr.setSelectedIndex(0);
         this.qulalification.setSelectedIndex(0);
         this.religion.setSelectedIndex(0);
         
        this.state_qid.setSelectedIndex(0);
        this.son.setSelected(false);
        this.disable.setSelected(false);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Enter dialog = new Enter(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox disable;
    private javax.swing.JComboBox gendr;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox nationality;
    private javax.swing.JComboBox qulalification;
    private javax.swing.JComboBox religion;
    private javax.swing.JTextField set_num;
    private javax.swing.JCheckBox son;
    private javax.swing.JComboBox state;
    private javax.swing.JComboBox state_qid;
    private javax.swing.JTextField telephone;
    // End of variables declaration//GEN-END:variables
}
