/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graduation_project;

import com.sun.jmx.snmp.BerDecoder;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ali
 */
public class grades extends javax.swing.JDialog {

   private float ar,en,fr,hi,goegraphy,psycholgy,phelosophy,ch,ph,math11,math22,geologya,statistic,EDpatriotism1,biology1,totall;
   private String st_ssn;
   
   
   
    public grades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.Student_id.setText(Enter.national);
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Student_id = new javax.swing.JTextField();
        english = new javax.swing.JTextField();
        Arabic = new javax.swing.JTextField();
        history = new javax.swing.JTextField();
        frensh = new javax.swing.JTextField();
        geography = new javax.swing.JTextField();
        philosophy = new javax.swing.JTextField();
        psychology = new javax.swing.JTextField();
        biology = new javax.swing.JTextField();
        chmistry = new javax.swing.JTextField();
        physics = new javax.swing.JTextField();
        math1 = new javax.swing.JTextField();
        math2 = new javax.swing.JTextField();
        geologia = new javax.swing.JTextField();
        statisics = new javax.swing.JTextField();
        EDpatriotism = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("ادخال درجات الطالب");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("الرقم القومي");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("اللغة العربية ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("اللغة الاجنبية الاولى");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("اللغة الاجنبية التانية ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("التاريخ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("الجغرافيا ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("الفلسفة والمنطق ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("علم النفس والاجتماع");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("الاحياء ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("الكيمياء");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("الفيزياء");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("الرياضيات البحتة ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("الرياضيات التطبيقية ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("الجولوجيا والعلوم البيئية ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("الاحصاء والاقتصاد");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("التربية الوطنية");

        frensh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenshActionPerformed(evt);
            }
        });

        psychology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psychologyActionPerformed(evt);
            }
        });

        biology.setText(" ");

        chmistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmistryActionPerformed(evt);
            }
        });

        geologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geologiaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("المجموع الكلى ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(statisics, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                                    .addComponent(EDpatriotism))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(geologia)
                                    .addComponent(physics)
                                    .addComponent(biology)
                                    .addComponent(chmistry)
                                    .addComponent(math1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(math2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(frensh, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(geography, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Student_id, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Arabic, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(philosophy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel4)
                                        .addGap(2, 2, 2))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(psychology, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel6)))))
                .addGap(174, 174, 174))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Student_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(biology, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Arabic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel13)
                        .addComponent(physics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(chmistry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(frensh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(math1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(math2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel8)
                    .addComponent(geography, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(statisics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(philosophy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(psychology, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(EDpatriotism, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("صورة النتيجة");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graduation_project/01.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton3.setBackground(new java.awt.Color(102, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("حذف");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("ادخال");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("بحث");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 153, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("الغاء");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 153, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 255));
        jButton7.setText("تعديل");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(121, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(563, 563, 563)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chmistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmistryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chmistryActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Dbase db=new Dbase();
       
         try {
             
        ar=Float.parseFloat(Arabic.getText().trim());
        en=Float.parseFloat(english.getText().trim());
        fr=Float.parseFloat(frensh.getText().trim());
        st_ssn=Student_id.getText().trim();
        totall=Float.parseFloat(total.getText().trim());
        
        if( EDpatriotism.getText().trim().equals(""))
            EDpatriotism1=-1;
        else 
        EDpatriotism1=Float.parseFloat(EDpatriotism.getText().trim());
      
      
         if( history.getText().trim().equals(""))
            hi=-1;
        else 
         hi=Float.parseFloat(history.getText().trim());
      
               if(chmistry.getText().trim().equals(""))
                   ch=-1;
          else
        ch=Float.parseFloat(chmistry.getText().trim());
               
           if(physics.getText().trim().equals(""))  
               ph=-1;
           else
        ph=Float.parseFloat(physics.getText().trim());
           
           if(math1.getText().trim().equals(""))
               math11=-1;
               else
        math11=Float.parseFloat(math1.getText().trim());
           
           if(math2.getText().trim().equals(""))
               math22=-1;
           else
        math22=Float.parseFloat(math2.getText().trim());
           
           if(geologia.getText().trim().equals(""))
               geologya=-1;
           else
        geologya=Float.parseFloat(geologia.getText().trim());
           
           
        statistic=Float.parseFloat(statisics.getText().trim());
        
        if(biology.getText().trim().equals("")) biology1=-1;
        else
        biology1=Float.parseFloat(biology.getText().trim());
        
        if(geography.getText().trim().equals(""))  
            goegraphy=-1;
        else
        goegraphy= Float.parseFloat(geography.getText().trim());
        
        if(philosophy.getText().trim().equals(""))
            
            phelosophy=-1;
        else
        phelosophy=Float.parseFloat(philosophy.getText().trim());
        
        if(psychology.getText().trim().equals(""))
            psycholgy=-1;
            else
        psycholgy=Float.parseFloat(psychology.getText().trim());
  
         String sql ="";
         if(file!=null)
         {
             sql="INSERT INTO  grades(`Arabic`,`total`, `english`, `frensh`, `history`, `geography`, `philosophy`, `psychology`, `biology`, `physics`, `math1`, `math2`, `chmistry`, `EDpatriotism`, `Student_ssn`, `statisics`, `geologia`,`resultImage`) "
                + " VALUES ("+ar+","+totall+", "+en+", "+fr+", "+hi+", "+goegraphy+", "+phelosophy+", "+psycholgy+", "+biology1+", "+ph+", "+math11+", "+math22+", "+ch+", "+EDpatriotism1+", "+st_ssn+", "+statistic+", "+geologya+",LOAD_FILE(?))";
           
                Dbase.st=Dbase.getConnection().prepareStatement(sql);
                 Dbase.st.setString(1,file.getPath());
                 Dbase.st.executeUpdate();
              
                 JOptionPane.showMessageDialog(null,"تم ادخال درجات الطالب");
                 clearTexts();
         }
         else
         {
            sql="INSERT INTO  grades(`Arabic`,`total`, `english`, `frensh`, `history`, `geography`, `philosophy`, `psychology`, `biology`, `physics`, `math1`, `math2`, `chmistry`, `EDpatriotism`, `Student_ssn`, `statisics`, `geologia`,`resultImage`) "
                + " VALUES ("+ar+","+totall+", "+en+", "+fr+", "+hi+", "+goegraphy+", "+phelosophy+", "+psycholgy+", "+biology1+", "+ph+", "+math11+", "+math22+", "+ch+", "+EDpatriotism1+", "+st_ssn+", "+statistic+", "+geologya+",NULL)";
           
                Dbase.st=Dbase.getConnection().prepareStatement(sql);
                 Dbase.st.executeUpdate();
              
                 JOptionPane.showMessageDialog(null,"تم ادخال درجات الطالب");
                 clearTexts();  
                 
                
         }
          file=null;
            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null, "لم يتم ادخال الدرجات ! ");
                Logger.getLogger(grades.class.getName()).log(Level.SEVERE, null, ex);
            }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

       
       st_ssn=Student_id.getText().trim(); 
        Dbase db=new Dbase();
        String sql ="DELETE FROM `grades` WHERE Student_ssn ='"+st_ssn+"'";
        
       if( db.executeSql(sql)==1)
       {
           JOptionPane.showMessageDialog(null, "تم مسح درجات الطالب");
           clearTexts();
       }
       else
       {
           JOptionPane.showMessageDialog(null, "لم يتم مسح درجات الطالب حاول مره اخرى");
       }
        
    }//GEN-LAST:event_jButton3ActionPerformed
public Image resizeimage(Image img,int w,int h)
     {
         BufferedImage reimg = new BufferedImage(w,h,BufferedImage.TYPE_INT_ARGB);
         Graphics2D g = reimg.createGraphics();
         g.drawImage(img, 0, 0,w,h,null);
         g.dispose();
         return  reimg;
     }
    FileInputStream fin;  File file=null;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
               byte [] personimage =null;

         JFileChooser f =new JFileChooser();
            f.showOpenDialog(null);
            
           file = f.getSelectedFile();
            
            try{
              fin  = new FileInputStream(file);
                
                ByteArrayOutputStream bo = new ByteArrayOutputStream();
                byte [] buf  =new byte[1024];
                for(int i; (i=fin.read(buf))!=-1; )
                {
                  bo.write(buf, 0, i);
                }
                
                personimage =bo.toByteArray();
                ImageIcon im =new ImageIcon(personimage);
                jLabel20.setIcon(new ImageIcon(resizeimage(im.getImage(),jLabel20.getWidth(),jLabel20.getHeight())));
                
            }catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        String sql="select * from grades where Student_ssn='"+Student_id.getText()+"'";
         Dbase db=new Dbase();
         ResultSet rs=null;
         rs=db.executeSelect(sql);
         try
         {
         if(rs.next())
         {
             Arabic.setText(rs.getString("Arabic"));
             total.setText(rs.getString("total"));
             english.setText(rs.getString("english"));
             frensh.setText(rs.getString("frensh"));
             history.setText(rs.getString("history"));
             geography.setText(rs.getString("geography"));
             philosophy.setText(rs.getString("philosophy"));
             psychology.setText(rs.getString("psychology"));
             biology.setText(rs.getString("biology"));
             physics.setText(rs.getString("physics"));
             chmistry.setText(rs.getString("chmistry"));
             math1.setText(rs.getString("math1"));
             math2.setText(rs.getString("math2"));
             geologia.setText(rs.getString("geologia"));
             statisics.setText(rs.getString("statisics"));
             EDpatriotism.setText(rs.getString("EDpatriotism"));
             byte image [] = rs.getBytes("resultImage");
             ImageIcon ic=new ImageIcon(image);
             jLabel20.setIcon(new ImageIcon(resizeimage(ic.getImage(), jLabel20.getWidth(),jLabel20.getHeight())));
             
         }
         else
         {
         JOptionPane.showMessageDialog(null, "هذا الطالب غير موجود");
         
         }
         }
         catch(SQLException S)
         {
             JOptionPane.showMessageDialog(null,S.getMessage());
         }
         

    }//GEN-LAST:event_jButton1ActionPerformed

    public  void clearTexts()
    {
             Student_id.setText("");
             Arabic.setText("");
             english.setText("");
             frensh.setText("");
             history.setText("");
             geography.setText("");
             philosophy.setText("");
             psychology.setText("");
             biology.setText("");
             physics.setText("");
             chmistry.setText("");
             math1.setText("");
             math2.setText("");
             geologia.setText("");
             statisics.setText("");
             EDpatriotism.setText("");
             total.setText("");
              jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graduation_project/01.png")));
    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     
       Dbase db=new Dbase();
        ar=Float.parseFloat(Arabic.getText().trim());
        en=Float.parseFloat(english.getText().trim());
        fr=Float.parseFloat(frensh.getText().trim());
        hi=Float.parseFloat(history.getText().trim());
        ch=Float.parseFloat(chmistry.getText().trim());
        ph=Float.parseFloat(physics.getText().trim());
        math11=Float.parseFloat(math1.getText().trim());
        math22=Float.parseFloat(math2.getText().trim());
        geologya=Float.parseFloat(geologia.getText().trim());
        statistic=Float.parseFloat(statisics.getText().trim());
        EDpatriotism1=Float.parseFloat(EDpatriotism.getText().trim());
        biology1=Float.parseFloat(biology.getText().trim());
        goegraphy= Float.parseFloat(geography.getText().trim());
        phelosophy=Float.parseFloat(philosophy.getText().trim());
        psycholgy=Float.parseFloat(psychology.getText().trim());
        st_ssn=Student_id.getText().trim();
        totall=Float.parseFloat(total.getText().trim());
        
        
        
        String sql="UPDATE `grades`"
                + " SET `total`="+totall+",`Arabic`="+ar+",`english`="+en+",`frensh`="+fr+","
                + "`history`="+hi+",`geography`="+goegraphy+",`philosophy`="+phelosophy+",`psychology`="+psycholgy+","
                + "`biology`="+biology1+",`physics`="+ph+",`math1`="+math11+",`math2`="+math22+",`chmistry`="+ch+","
                + "`EDpatriotism`="+EDpatriotism1+",`Student_ssn`="+st_ssn+",`statisics`="+statistic+","
                + "`resultImage`=LOAD_FILE(?),"
                + "`geologia`="+geologya+" WHERE `Student_ssn` like '"+Student_id.getText()+"'";
        try{
            
            if(file !=null)
            {
             sql="UPDATE `grades`"
                + " SET `total`="+totall+",`Arabic`="+ar+",`english`="+en+",`frensh`="+fr+","
                + "`history`="+hi+",`geography`="+goegraphy+",`philosophy`="+phelosophy+",`psychology`="+psycholgy+","
                + "`biology`="+biology1+",`physics`="+ph+",`math1`="+math11+",`math2`="+math22+",`chmistry`="+ch+","
                + "`EDpatriotism`="+EDpatriotism1+",`Student_ssn`="+st_ssn+",`statisics`="+statistic+","
                + "`resultImage`=LOAD_FILE(?),"
                + "`geologia`="+geologya+" WHERE `Student_ssn` like '"+Student_id.getText()+"'";
                   Dbase.st=Dbase.getConnection().prepareStatement(sql);
                   Dbase.st.setString(1,file.getPath());
                   Dbase.st.executeUpdate();
                   JOptionPane.showMessageDialog(null,"تم تحديث  البيانات ");
                   clearTexts();
            }else
            {
                sql="UPDATE `grades`"
                + " SET `total`="+totall+",`Arabic`="+ar+",`english`="+en+",`frensh`="+fr+","
                + "`history`="+hi+",`geography`="+goegraphy+",`philosophy`="+phelosophy+",`psychology`="+psycholgy+","
                + "`biology`="+biology1+",`physics`="+ph+",`math1`="+math11+",`math2`="+math22+",`chmistry`="+ch+","
                + "`EDpatriotism`="+EDpatriotism1+",`Student_ssn`="+st_ssn+",`statisics`="+statistic+","
               
                + "`geologia`="+geologya+" WHERE `Student_ssn` like '"+Student_id.getText()+"'";
                   Dbase.st=Dbase.getConnection().prepareStatement(sql);
                   Dbase.st.executeUpdate();
                   JOptionPane.showMessageDialog(null,"تم تحديث  البيانات ");
                   clearTexts(); 
            }
        
       
         
        }
       catch(Exception ex)
               {
               JOptionPane.showMessageDialog(null, "لم يتم تحديث البيانات");
               }
 
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void psychologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psychologyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psychologyActionPerformed

    private void frenshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frenshActionPerformed

    private void geologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geologiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                grades dialog = new grades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Arabic;
    private javax.swing.JTextField EDpatriotism;
    private javax.swing.JTextField Student_id;
    private javax.swing.JTextField biology;
    private javax.swing.JTextField chmistry;
    private javax.swing.JTextField english;
    private javax.swing.JTextField frensh;
    private javax.swing.JTextField geography;
    private javax.swing.JTextField geologia;
    private javax.swing.JTextField history;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField math1;
    private javax.swing.JTextField math2;
    private javax.swing.JTextField philosophy;
    private javax.swing.JTextField physics;
    private javax.swing.JTextField psychology;
    private javax.swing.JTextField statisics;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
