/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graduation_project;

import java.io.FileOutputStream;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Row;
/**
 *
 * @author Ali
 */
public class tansiq extends javax.swing.JDialog {
String []desir ={"الفة الاجنبية الاولى","االلغة الفرنسية "," التاريخ ","الجغرافيا ","الفلسفة","علم النفس","الاجتماع ","الدراسات السكانية ","علوم المسرح","اللغة العربية ","الدراسات الاسلامية ","الاثار","المكتبات","الاعلام"};
    public tansiq(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        String g="SELECT deptname FROM `department` ORDER BY dept_id ASC";
        Dbase.fillcompo(jComboBox1,g);
    }

    public    st n [] =null;
    public    dept d [] =new dept[14];
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jComboBox1 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("توزيع الطلاب حسب الرغبات ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(86, 86, 86))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("توزيع الطلاب ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("حفظ البيانات لقسم معين ملف اكسل ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("تقرير لحفظ البيانات لقسم معين ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDesktopPane1))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
try {
        int len=0;
        String s ="select count(*) from student";
         ResultSet rss = Dbase.executeSelect(s);
         
         if(rss.next()){len=rss.getInt(1); }
         
         n=new st[len];
         for(int k=0;k<len;k++)
         {
             n[k]=new st();
         }
     
        String sql = "select * from student";
        int i = 0;
        ResultSet rs = Dbase.executeSelect(sql);     
            while (rs.next()) {
        
                n[i].ssn = rs.getString("ssn");
                n[i].qualify = rs.getInt("qualification");
                n[i].son = rs.getInt("sons_of_employees");
                n[i].disable = rs.getInt("disAble");
                
                String sql2 = "select * from grades where Student_ssn='"+n[i].ssn+"'";
                ResultSet rs2 = Dbase.executeSelect(sql2);
                if (rs2.next()) {
                    n[i].ar = rs2.getFloat("Arabic");
                    n[i].en = rs2.getFloat("english");
                    n[i].fr = rs2.getFloat("frensh");
                    n[i].biology1 = rs2.getFloat("biology");
                    n[i].EDpatriotism1 = rs2.getFloat("EDpatriotism");
                    n[i].ch = rs2.getFloat("chmistry");
                    n[i].geologya = rs2.getFloat("geologia");
                    n[i].goegraphy = rs2.getFloat("geography");
                    n[i].hi = rs2.getFloat("history");
                    n[i].math11 = rs2.getFloat("math1");
                    n[i].math22 = rs2.getFloat("math2");
                    n[i].ph = rs2.getFloat("physics");
                    n[i].phelosophy = rs2.getFloat("philosophy");
                    n[i].psycholgy = rs2.getFloat("psychology");
                    n[i].statistic=rs2.getFloat("statisics");
                    n[i].totall=rs2.getFloat("total");
               
                }
              String sql3="SELECT * FROM `desires` WHERE `Student_ssn` LIKE '"+n[i].ssn+"'";
               ResultSet rs3 = Dbase.executeSelect(sql3);
               
              if(rs3.next())
              {
                      for(int j =0;j<14;j++)
                      n[i].desire[j]=rs3.getInt("d"+(j+1));
              }
              
                    i++;
            }
          
          int count [] = new int [14];
          Calendar now = Calendar.getInstance();   // Gets the current date and time
         int year = now.get(Calendar.YEAR);
          for(int m=0;m<count.length;m++)
          {
              
              String sq ="select studentNumber from deptyear where dept_id="+m+" and year ='"+year+"'";
             ResultSet rr= Dbase.executeSelect(sq);
             if(rr.next())
             {
                 count[m]=rr.getInt(1);
             }   
          }
          for(int v=0;v<d.length;v++)
          {
              d[v]=new dept(count[v]);
          }
          
          mm();
      for (int h=0;h<d.length;h++)
      {
          for(int z=0;z<d[h].s.length;z++)
          {
          String sss ="UPDATE `student` Set `dept_id`="+h+" WHERE `ssn` ='"+d[h].s[z].ssn+"'";
          if(Dbase.executeSql(sss)==1)  
              System.out.println("yesss ");
          
           }
          
      }
   /***  statics ***/   
      Statics [] sc  = new Statics[14];
      for(int p=0;p<14;p++)
          sc[p] = new Statics();
      
      for (int yy=0;yy<14;yy++)
      {
          // male 
          String sss1 ="SELECT count(*) FROM `student` WHERE `dept_id`="+yy+" and `gend_id`=1";
          ResultSet rs1 = Dbase.executeSelect(sss1);
          if(rs1.next())
          {
              sc[yy].male=rs1.getInt(1);
          }
          // female
           String sss2 ="SELECT count(*) FROM `student` WHERE `dept_id`="+yy+" and `gend_id`=2";
          ResultSet rs2 = Dbase.executeSelect(sss2);
          if(rs2.next())
          {
              sc[yy].female=rs2.getInt(1);
          }
          
          sc[yy].total = sc[yy].female+sc[yy].male;
          
          String Aby ="select count(*) from student where `qualification`= 2 and `dept_id`="+yy;
           ResultSet adby = Dbase.executeSelect(Aby);
          if(adby.next())
          {
              sc[yy].adby=adby.getInt(1);
          }
          String mohalat ="select count(*) from student where `qualification`= 3 and `dept_id`="+yy;
           ResultSet moh = Dbase.executeSelect(mohalat);
          if(moh.next())
          {
              sc[yy].mohalat=moh.getInt(1);
          }
          
          sc[yy].almy =sc[yy].total-(sc[yy].mohalat+sc[yy].adby);
          
          if(d[yy].cur!=0)
          sc[yy].grade=d[yy].s[d[yy].cur-1].grade;
          
      }
   
      for(int oo=0;oo<14;oo++)
      {
       
          String stt="INSERT INTO `statics` (`total`, `male`, `female`, `letrary`,"
                  + " `scientific`, `qulaification`, `grade`, `dept_id`, `year`) "
                  + "VALUES ('"+sc[oo].total+"', '"+sc[oo].male+"', '"+sc[oo].female+"',"
                  + "'"+sc[oo].adby+"', '"+sc[oo].almy+"', '"+sc[oo].mohalat+"', "
                  + "'"+sc[oo].grade+"', '"+oo+"', '"+Calendar.getInstance().get(Calendar.YEAR)+"')";
          
          Dbase.executeSql(stt);
          System.out.println("yyyyyyyyeeeeeessss");
          System.out.println(sc[oo].total);
      }
 
      Dbase.op("تم توزيع الطلاب بنجاح ");
        } 
        catch (Exception ex) {     
            System.out.println("the exception is " + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       try{
              int index= jComboBox1.getSelectedIndex();
        String sql="select name,ssn from student where dept_id="+index;
        HSSFWorkbook wb = new HSSFWorkbook();
HSSFSheet personSheet = wb.createSheet("طلاب القسم ");
HSSFRow headerRow = personSheet.createRow(0);
HSSFCell nameHeaderCell = headerRow.createCell(0);
HSSFCell addressHeaderCell = headerRow.createCell(1);

         
            ResultSet rs= Dbase.executeSelect(sql);
         
         HSSFRow data = personSheet.createRow(0);

    HSSFCell c = data.createCell(0);
    
    c.setCellValue("الاســــــــــم ");

    HSSFCell d = data.createCell(1);
     
    d.setCellValue("الرقم القـــــــومي ");
    /***/
            
         int row =1;
      
         while (rs.next()){
             
         String name=  rs.getString("name");
         String ssn=rs.getString("ssn");
       
    HSSFRow dataRow = personSheet.createRow(row);

    HSSFCell dataNameCell = dataRow.createCell(0);
    
    dataNameCell.setCellValue(name);

    HSSFCell dataAddressCell = dataRow.createCell(1);
     
    dataAddressCell.setCellValue(ssn);

    row = row + 1;
                }
      String path="";
        JFileChooser jc = new JFileChooser();
             int chooservalue = jc.showSaveDialog(this);
             if(chooservalue==JFileChooser.APPROVE_OPTION)
             {
               path = jc.getSelectedFile().getAbsolutePath();
             }
        String out = path+".xls";  

        FileOutputStream fileOut;
      
             fileOut = new FileOutputStream(out);
             wb.write(fileOut);
             fileOut.close();
             Dbase.op("تم حفظ الملف ف "+out);
                }catch(Exception ex)
                {
                   Dbase.op(ex.getMessage());
                } 
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         try{
             int i = this.jComboBox1.getSelectedIndex();
             String dep = this.jComboBox1.getSelectedItem().toString();
             Map m=new HashMap();
            //m.put("proName", "General"); //Parameters to be sent to report
            m.put("deptid",i);//Parameter to be sent to report
            m.put("deptname","اسماء طلاب قسم "+dep);
            String report="F:\\desktop\\Netbeans\\graduation_project\\src\\report\\department.jrxml";
            
            JasperReport jasperReport = JasperCompileManager.compileReport(report);
           
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, m,Dbase.getConnection());
           // JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint);
            this.setVisible(false);
        }
        catch (Exception e){
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tansiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tansiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tansiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tansiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tansiq dialog = new tansiq(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public  void mm(){
        
    
     try{
        for(int i=0;i<n.length;i++)
        {
          
        // n[i].show();
            dist(i,0);
        }
     }catch(Exception ex){System.out.println("...."+ex);}
        for(int j=0;j<d.length;j++)
        {
            System.out.println("dept "+j+ "********");
        {
           for(int k=0;k<d[j].s.length;k++)
                System.out.println(" "+d[j].s[k].ssn);
        }
        }
    }
    
    public int re(String ss)
    {
        for(int i =0;i<n.length;i++)
        {
            if(n[i].ssn == ss)
                return i;
        }
        return 0; 
    }
    
     public void dist (int i , int des)
  {
      if(des>13 )return ;
               float grad =  n[i].grade(n[i].desire[des]);
               
             if(n[i].son==1 || n[i].qualify==3 || n[i].disable==1){ grad=1000;}
        
         int k = n[i].desire[des];  
         if(k==-1) return ;
         String  c=n[i].ssn;
      if(d[k].s.length>d[k].cur)
      {
          int y=d[k].cur;  String s =n[i].ssn;  float g = n[i].grade(des); int op = n[i].cur;
          
          
          d[k].s[y].set(s,grad,op);
          d[k].cur++;
          
            for (int p = 0; p<d[k].cur-1; p++)
    {
        for (int j = p+1;j<d[k].cur; j++)
        {
            if (d[k].s[p].grade < d[k].s[j].grade)
            {
              String sn1= d[k].s[p].ssn;
             float  grad1=d[k].s[p].grade;
              int cc1=d[k].s[p].curr;
              
                d[k].s[p].ssn = d[k].s[j].ssn;
                d[k].s[p].curr = d[k].s[j].curr;
                d[k].s[p].grade = d[k].s[j].grade;
                
                d[k].s[j].ssn = sn1;
                d[k].s[j].grade = grad1;
                d[k].s[j].curr = cc1;
            }
        }
    }
     
          
      }
      else if(d[k].cur>=d[k].s.length-1)
      {
         // System.out.println(""+d[k].s[d[k].s.length-1].grade);
          if(d[k].s[d[k].s.length-1].grade>=grad)
          {
              dist(i,++des);
          }
          else{
              
              String sn =d[k].s[d[k].cur-1].ssn; 
              int curd  = d[k].s[d[k].s.length-1].curr;
              float g = d[k].s[d[k].s.length-1].grade;    
              
              
              d[k].s[d[k].s.length-1].set(n[i].ssn,grad,n[i].cur);
              
              // d[k].s[d[k].s.length-1].ssn=n[i].ssn;
              // d[k].s[d[k].s.length-1].grade=n[i].grade(k);
              
          for (int p = 0; p<d[k].cur-1; p++)
    {
              for (int j = p+1;j<d[k].cur; j++)
        {
            if (d[k].s[p].grade < d[k].s[j].grade)
            {
              String sn1= d[k].s[p].ssn;
              float grad1=d[k].s[p].grade;
              int cc1=d[k].s[p].curr;
              
                d[k].s[p].ssn = d[k].s[j].ssn;
                d[k].s[p].curr = d[k].s[j].curr;
                d[k].s[p].grade = d[k].s[j].grade;
                
                d[k].s[j].ssn = sn1;
                d[k].s[j].grade = grad1;
                d[k].s[j].curr = cc1;
            }
        }
    }
              dist(re(sn),++curd);
          }
      }
    
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
